### ISSUE TITLE
Questions about the flags

### ISSUE THREAD

**Issue by xihuai18** [ZifanWu/Coordinated-PPO#1]
Does the flag `if_detach_others == True` mean that **all** the agents should be updated towards optimizing the **individual** advantage objective of some agent, e.g., agent `i`?

**Comment by ZifanWu** [comment]
It is `False` that implements the option you mentioned, which is actually abandoned due to the performance.

**Comment by xihuai18** [comment]
I make a mistake in the question, in
https://github.com/ZifanWu/Coordinated-PPO/blob/1a49e684b80e11a93a2bd0e56d5dd73673784411/onpolicy/config.py#L166

Does this flag == False mean that **all** the agents should be updated towards optimizing the **individual** advantage objective of some agent, e.g., agent `i`?

https://github.com/ZifanWu/Coordinated-PPO/blob/1a49e684b80e11a93a2bd0e56d5dd73673784411/onpolicy/algorithms/r_mappo/r_mappo.py#L159-L173

**Comment by ZifanWu** [comment]
Yes.

**Comment by xihuai18** [comment]
I have another question.
https://github.com/ZifanWu/Coordinated-PPO/blob/1a49e684b80e11a93a2bd0e56d5dd73673784411/onpolicy/config.py#L175

Is `clip_before_prod` set to be `True`? 
https://github.com/ZifanWu/Coordinated-PPO/blob/1a49e684b80e11a93a2bd0e56d5dd73673784411/onpolicy/algorithms/r_mappo/r_mappo.py#L174-L182

But then the `double_clip` branch will not be executed.

**Comment by ZifanWu** [comment]
No, because `clip_before_prod=True` is actually abandoned.

**Comment by xihuai18** [comment]
Would you like to update the `config.py` file and run scripts for re-producibility?

**Comment by xihuai18** [comment]
For example, the outer clip parameter
https://github.com/ZifanWu/Coordinated-PPO/blob/1a49e684b80e11a93a2bd0e56d5dd73673784411/onpolicy/config.py#L171

https://github.com/ZifanWu/Coordinated-PPO/blob/1a49e684b80e11a93a2bd0e56d5dd73673784411/onpolicy/algorithms/r_mappo/r_mappo.py#L135

https://github.com/ZifanWu/Coordinated-PPO/blob/1a49e684b80e11a93a2bd0e56d5dd73673784411/onpolicy/algorithms/r_mappo/r_mappo.py#L179-L182

Is selected to be `0.30`, which is diffierent with that claimed in the paper

**Comment by ZifanWu** [comment]
Sorry for forgetting to delete some abandoned options. The config file and run scripts are updated now.
